name: Unit Tests

on: [pull_request, push]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: pnpm install global
        run: npm i -g pnpm
      - name: deps install
        run: pnpm i
      - name: tests
        run: pnpm test